#Even Fibonacci numbers
#Problem 2 
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#def fibonacci(n)
#    first = 1
#    second = 2
#    third = first + second
#    fib_arr = [first, second, third]
#    while third < n
#        fib_arr.push(third)
#        first = second
#        second = third
#        third = first + second
#    end
#    #puts("Fib arr is: ", fib_arr)
#    x = 0
#    even_sum = 0
#    while x < fib_arr.size
#        current = fib_arr[x]
#        if current % 2 == 0
#            even_sum += current
#        end
#        x += 1
#    end
#    even_sum
#end
#    
#puts(fibonacci(10))
#puts(fibonacci(4000000))

#Largest prime factor
#Problem 3 
#The prime factors of 13195 are 5, 7, 13 and 29.
#
#What is the largest prime factor of the number 600851475143 ?


